### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by ManiacPC** [MhAllan/Xeeny#10]
Greets,

I dont know if its a bug or something, but I try to install from nuget the version 1.2.3 and it says that Xeeny doesnt have a compatible version for .NET Framework 4.5.2 or 4.6.1.

Thank you !

**Comment by MhAllan** [comment]
Hi, Are you using packages.config for referencing nuget? if so please upgrade your solution to use packagereference. https://marketplace.visualstudio.com/items?itemName=CloudNimble.NuGetPackageReferenceUpgrader
