### ISSUE TITLE
Can this do IPC with NamedPipes?

### ISSUE THREAD

**Issue by GammaSoul** [MhAllan/Xeeny#11]
Hi i came across this looking for a solid solution to communicate between some personal .net core 2.0 applications im working on. I was wondering if i can do NamedPipe IPC with it? i notice that i can setup custom transports with it. How would i setup a namedpipe transport? Sorry im new to c# just wondering if you had an example custom transport
Thank you

**Comment by MhAllan** [comment]
Named pipes is internal windows only transport so you can use full .net framework instead of core. you can use WCF for that. you still can implemented in Xeeny but WCF is ready for you.
