### ISSUE TITLE
Fragmented messages using JsonSerializer sometimes don't send properly

### ISSUE THREAD

**Issue by PCavan** [MhAllan/Xeeny#7]
There seems to be some kind of heisenbug when sending long messages using JsonSerializer - the receiving end gets a fragment with no header information somehow. I've [uploaded a project to my fork](https://github.com/PCavan/Xeeny/tree/develop/Src/Xeeny.FragmentBug) demonstrating the issue.

If I put a conditional breakpoint on SocketBase.Listen (as below), everything seems to run just fine:

![image](https://user-images.githubusercontent.com/29520239/36795168-3af27c56-1c9a-11e8-9626-f66c27d3e22f.png)

But if I disable it, I almost immediately get an exception because it doesn't recognise the message type:

![image](https://user-images.githubusercontent.com/29520239/36795270-82ba68dc-1c9a-11e8-9d34-5af2fa07616d.png)

On the iteration of the loop which threw the exception, `count` contains a value which would have triggered the breakpoint:

![image](https://user-images.githubusercontent.com/29520239/36795339-b1ce68c6-1c9a-11e8-949b-fc930a674fa8.png)

**Comment by PCavan** [comment]
On a bit of further investigation, it seems that the fragments all get sent ok, but sometimes the client will only read part of one, then the next read picks up where the previous one finished. I think this comes down to the SocketBase treating received data as packets, where TCP is stream based. I believe I have seen a related issue where two messages are sent in quick succession (or in parallel), and the client's receive buffer is filled with the end of one message and the start of the next.

**Comment by MhAllan** [comment]
I am working on different message framing. the current FragmentFormatter introduced the problem you mentioned plus it degrades the TCP performance because it tries to meet UDP requirements (fragments re-order). I hope I can commit in 2 days.

**Comment by MhAllan** [comment]
Hi, sorry for being late on this. I have fixed message framing for streaming transport. please check the new version and let me know if things are still wrong.
