### ISSUE TITLE
New logo for Xeeny

### ISSUE THREAD

**Issue by reallinfo** [MhAllan/Xeeny#8]
I wanted to contribute toXeeny. I designed a logo for Xeeny. If you like it, I'll send you the files.

![xeeny](https://user-images.githubusercontent.com/36298335/37867660-585210a0-2fa4-11e8-8de4-78d748c71e73.jpg)

**Comment by MhAllan** [comment]
I love it, please do =)

**Comment by reallinfo** [comment]
Okay, I will prepare the files. Which one do you prefer? Left or right? :)

**Comment by MhAllan** [comment]
left is great, many thanks

**Comment by reallinfo** [comment]
Here are all the files. Do not forget to write if you have another request. Good works!

https://drive.google.com/open?id=1Y9Taujj9lMOY6xPEyXs0-WqirjLtHmgQ

**Comment by reallinfo** [comment]
Hello @MhAllan I updated the readme. Please check it.

https://github.com/MhAllan/Xeeny/pull/9

**Comment by MhAllan** [comment]
I have merged it, I will include this logo in the next nuget version. Many thanks =)
